import { Toaster } from "react-hot-toast";
import { CartProvider } from "../components/Cart/CartContext";
import "../globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Client 5",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} textx-[13px] antialiased`}>
        <CartProvider>
          <Toaster
            position="top-left"
            toastOptions={{
              style: {
                fontFamily: "Roboto,sans-serif",
                fontSize: "13px",
                background: "#333",
                color: "#fff",
                borderRadius: "8px",
              },
            }}
          />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
